# Generated by Django 2.2.3 on 2019-08-18 14:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_football'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='football',
            name='name',
        ),
        migrations.RemoveField(
            model_name='football',
            name='user',
        ),
        migrations.AddField(
            model_name='football',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
