# Generated by Django 2.2.3 on 2019-08-18 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190817_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=100)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='cover/%Y/%m/%D/')),
                ('website', models.URLField(blank=True, null=True)),
                ('description', models.TextField()),
                ('sample', models.FileField(blank=True, null=True, upload_to='chapters/%Y/%m/%D/')),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.POST'),
        ),
    ]
